In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset

dataset = load_dataset("lukebarousse/data_jobs")
df=dataset["train"].to_pandas()

df["job_posted_date"] = pd.to_datetime(df["job_posted_date"])

c:\Users\moham\anaconda3\envs\luke_py\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [19]:
df.loc[:10,"salary_year_avg":"salary_hour_avg"]

    salary_year_avg  salary_hour_avg
0               NaN              NaN
1               NaN              NaN
2               NaN              NaN
3               NaN              NaN
4               NaN              NaN
5               NaN              NaN
6               NaN              NaN
7               NaN              NaN
8               NaN              NaN
9               NaN              NaN
10              NaN              NaN

In [20]:
med_year = df.salary_year_avg.median()

In [21]:
med_hour = df.salary_hour_avg.median()

In [26]:
df_filled = df 

df_filled.salary_year_avg = df_filled.salary_year_avg.fillna(med_year)
df_filled.salary_hour_avg = df_filled.salary_hour_avg.fillna(med_hour)

In [32]:
df_filled.loc[:10,"salary_year_avg":"salary_hour_avg" ]

    salary_year_avg  salary_hour_avg
0          115000.0            45.98
1          115000.0            45.98
2          115000.0            45.98
3          115000.0            45.98
4          115000.0            45.98
5          115000.0            45.98
6          115000.0            45.98
7          115000.0            45.98
8          115000.0            45.98
9          115000.0            45.98
10         115000.0            45.98

In [55]:
df_un = df_filled

In [56]:
df_un = df_un.drop_duplicates()

In [57]:
df_un = df_un.drop_duplicates(subset=["job_title" ,"company_name"])